[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "npm run build",
  "npx playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "node dist/main.js"

[variables]
NODE_ENV = "production"
PORT = "3001"
